### ISSUE TITLE
The vundle plugin 

### ISSUE THREAD

**Issue by zhangsiyu1103** [dijkstracula/vim-ivy#1]
I believe for vundle installation, you may need to add 

Plugin 'dijkstracula/vim-ivy' to ~/.vimrc 

instead of 

Plugin 'dijkstracula/vim-ivy.vim' to ~/.vimrc

**Comment by dijkstracula** [comment]
Hi,

Thanks for the issue.  To confirm: when you say "you may need to add ...", did you verify that the `.vim` extension is needed?  (I ask because I don't use Vundle, but other plugins [such as golang](https://github.com/fatih/vim-go) don't seem to require it, and ones that do [such as rust](https://github.com/rust-lang/rust.vim) appear to have that suffix as part of the repo name.)

Thanks!

**Comment by zhangsiyu1103** [comment]
Actually, what I mean is we don't need '.vim' extension when using vundle because in your readme instruction there is a '.vim' extension. Yes, I tested it with vundle and it does not work with the '.vim' extension.

**Comment by dijkstracula** [comment]
Oh, sorry, I misread both your comment as well as my own README!  Fixing; thank you.

**Comment by dijkstracula** [comment]
Fixed as of 9fba573fa70e11e121b3ec1bd2e18642d2340c58 .
